export class Modification {
    
  public ident: number;

  constructor( public idTache: number, public donnee: Donnee, public valeurAvant: string, public valeurApres: string) {

  }
}

export enum Donnee {
  MARQUE_VEHICULE,
  MODELE_VEHICULE,
  DESIGNATION_VEHICULE,
  IMMATRICULATION_VEHICULE,
  MEC_VEHICULE,
  MA_VEHICULE,
  DA_VEHICULE,
  NUMERO_PERMIS,
  CATEGORIE_PERMIS,
  DATE_PERMIS,
  DEPARTEMENT_PERMIS,
  PREFECTURE_PERMIS,
  CRM_CONDUCTEUR, 
  CRM2_CONDUCTEUR,
  DOCRM05_CONDUCTEUR,
  RESP100_CONDUCTEUR,
  RESP50_CONDUCTEUR,
  RESP0_CONDUCTEUR,
  VI_CONDUCTEUR,
  BDG_CONDUCTEUR,
  STATIONNEMENT_CONDUCTEUR
}
  